#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
fi
exit 0
